# Generated by Django 5.2 on 2025-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newletter_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
